### ISSUE TITLE
no-margin-for-errors (plugin website) website is hacked

### ISSUE THREAD

**Issue by ammist** [scaron/prettyphoto#186]
I clicked on the website for this plugin (referenced in README.md) to get some documentation and got a password popup and an audio loop that said something like "Microsoft Alert.  Spyware has been found on your computer, please enter your username and password."  I'm on a mac, so this looks even more suspicious than it would normally look.

Don't click on the links to no-margin-for-errors until this is fixed.

**Comment by scaron** [comment]
Hi Anca,

I am unable to reproduce the issue.

Google reports the website as being safe: https://transparencyreport.google.com/safe-browsing/search?url=www.no-margin-for-errors.com

**Comment by cezarpopa** [comment]
This is still an issue, manage to replicate it on two different android devices and a Windows 10 machine Kaspersky reports a malicious link from your website, do a grep for 5.45.67.97 or check the developer toolbar.
later edit:
https://sitecheck.sucuri.net/results/www.no-margin-for-errors.com/

**Comment by scaron** [comment]
My mistake.

I confirm this is now fixed.

https://sitecheck.sucuri.net/results/no-margin-for-errors.com

Thanks.

**Comment by cezarpopa** [comment]
Glad to hear it's sorted.
