### ISSUE TITLE
Overlay gallery not showing all thumbs

### ISSUE THREAD

**Issue by cs-pPGallery** [scaron/prettyphoto#30]
Hi,
just observed when having large galleries with e.g. more than 20 images, not all images are beeing represented in the overly-gallery. E.g. I have a gallery with 55 images and when scrolling (in the overlay gallery) to the end, it stops at image no. 50 (than scrolls back)!
I could not figure out at what amount of images that happens, must be somewhere more than 20...
regards.

**Comment by ivehapers** [comment]
Hi there,
I'm also looking for my problem to solve: the overlay gallery 's only shown when the map has les than 30 images.  How can I solve this?
Thanks
